title: Manish Reddy
subtitle: Machine Learning & Generative AI Engineer
description: Enterprise-grade Generative AI, LLMs, RAG, MLOps, Cloud

url: "https://manishr17.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Manish Reddy
  avatar: /assets/profile.jpg   # optional but recommended
  bio: Machine Learning & Generative AI Engineer
  location: Dallas, TX
  links:
    - label: Email
      icon: fas fa-envelope
      url: mailto:manishyr55@gmail.com
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/manishr17
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/manishr-ai/

header_pages:
  - index.md
  - projects.md
  - experience.md
  - skills.md
  - certifications.md
  - resume.md

search: false
breadcrumbs: false
